#!/bin/bash

set -eu

PLATFORM=$(uname -s)
ARCHITECTURE=$(uname -m)
NODE_VERSION=$(node --version)
PACKAGE_HASH=$(hash_file pnpm-lock.yaml)

if [ -d patches ]; then
  PATCHES_HASH=$(hash_directory patches/)
else
  PATCHES_HASH=nopatch
fi

CACHEKEY="$BUILDKITE_PIPELINE_SLUG-pnpm-$PLATFORM-$ARCHITECTURE-node-$NODE_VERSION-$PACKAGE_HASH-$PATCHES_HASH"

LOCAL_PNPM_CACHE=./vendor/pnpm
mkdir -p $LOCAL_PNPM_CACHE

echo "--- :pnpm: Restore pnpm cache if present"
restore_cache "$CACHEKEY"

echo "--- :pnpm: Install Node dependencies"

corepack enable pnpm

echo "pnpm node-linker: $(pnpm config get node-linker)"

pnpm install \
  --store-dir $LOCAL_PNPM_CACHE \
  --frozen-lockfile

cd cli
pnpm install \
  --store-dir $LOCAL_PNPM_CACHE \
  --frozen-lockfile
cd -

echo "--- :pnpm: Verify installation"
# Check that critical dependencies are accessible
echo "Checking critical dependencies..."

# Check root dependencies
if [ -d "node_modules/@php-wasm/node" ]; then
  echo "✓ @php-wasm/node found in root"
else
  echo "✗ @php-wasm/node NOT found in root"
  exit 1
fi

if [ -d "node_modules/@wp-playground/cli" ]; then
  echo "✓ @wp-playground/cli found in root"
else
  echo "✗ @wp-playground/cli NOT found in root"
  exit 1
fi

# Check CLI dependencies
if [ -d "cli/node_modules/pm2" ]; then
  echo "✓ pm2 found in cli"
else
  echo "✗ pm2 NOT found in cli"
  exit 1
fi

# Verify hoisted structure (not symlinks)
if [ -f "node_modules/@php-wasm/node/package.json" ]; then
  echo "✓ Hoisted mode working - files are real, not just symlinks"
else
  echo "✗ Package files not accessible"
  exit 1
fi

echo "All critical dependencies verified!"

echo "--- :pnpm: Save cache if necessary"
# Notice that we don't cache the local node_modules.
# Those get regenerated by pnpm install as per Node recommendations.
# What we are caching is the pnpm store, which stores package downloads.
save_cache "$LOCAL_PNPM_CACHE" "$CACHEKEY"
