import { app, utilityProcess, UtilityProcess } from 'electron';
import { PHPRunOptions } from '@php-wasm/universal';
import * as Sentry from '@sentry/electron/renderer';
import { WPNowOptions } from 'vendor/wp-now/src/config';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const SITE_SERVER_PROCESS_MODULE_PATH: string;

export type MessageName = 'start-server' | 'stop-server' | 'run-php';

const DEFAULT_RESPONSE_TIMEOUT = 120000;

export default class SiteServerProcess {
	lastMessageId = 0;
	options: WPNowOptions;
	processes: UtilityProcess[] = [];
	phpInstances: { documentRoot: string }[] = [];
	url: string;
	exitCode: number | null = null;
	private currentProcessIndex = 0;

	constructor( options: WPNowOptions ) {
		this.options = options;
		this.url = options.absoluteUrl ?? '';
	}

	private getNextProcess(): UtilityProcess {
		const process = this.processes[ this.currentProcessIndex ];
		this.currentProcessIndex = ( this.currentProcessIndex + 1 ) % this.processes.length;
		return process;
	}

	async start() {
		const numInstances = this.options.numberOfPhpInstances || 6;

		for ( let i = 0; i < numInstances; i++ ) {
			const processOptions = {
				...this.options,
				instanceId: i,
				projectPath: this.options.projectPath,
			};

			const forkedProcess = utilityProcess.fork(
				SITE_SERVER_PROCESS_MODULE_PATH,
				[ JSON.stringify( processOptions ) ],
				{
					serviceName: 'studio-site-server',
					env: {
						...process.env,
						STUDIO_IN_CHILD_PROCESS: 'true',
						STUDIO_APP_NAME: app.name,
						STUDIO_APP_DATA_PATH: app.getPath( 'appData' ),
						STUDIO_APP_LOGS_PATH: app.getPath( 'logs' ),
					},
				}
			);
			this.processes.push( forkedProcess );

			const result = await this.sendMessage( forkedProcess, 'start-server', {} );
			if ( result && result.php ) {
				this.phpInstances.push( result.php );
			}
		}
	}

	async stop() {
		await Promise.all(
			this.processes.map( async ( process ) => {
				const message = 'stop-server';
				const messageId = await this.sendMessage( process, message, {} );
				try {
					await this.waitForResponse( message, messageId, 5_000 );
				} finally {
					await this.#killProcess();
				}
			} )
		);
		this.processes = [];
		this.phpInstances = [];
	}

	async runPhp( data: PHPRunOptions ): Promise< string > {
		const process = this.getNextProcess();
		return await this.sendMessage( process, 'run-php', data );
	}

	async sendMessage(
		process: UtilityProcess,
		message: MessageName,
		data: unknown
	): Promise< any > {
		const messageId = ++this.lastMessageId;
		process.postMessage( { message, messageId, data } );
		return this.waitForResponse( message, messageId );
	}

	async waitForResponse< T = undefined >(
		originalMessage: MessageName,
		originalMessageId: number,
		timeout = DEFAULT_RESPONSE_TIMEOUT
	): Promise< T > {
		const process = this.getNextProcess();
		if ( ! process ) {
			throw Error( 'Server process is not running' );
		}

		return new Promise( ( resolve, reject ) => {
			const handler = ( {
				message,
				messageId,
				data,
				error,
			}: {
				message: MessageName;
				messageId: number;
				data: T;
				error?: Error;
			} ) => {
				if ( message !== originalMessage || messageId !== originalMessageId ) {
					return;
				}
				process.removeListener( 'message', handler );
				clearTimeout( timeoutId );
				if ( typeof error !== 'undefined' ) {
					reject( error );
					return;
				}
				resolve( data );
			};

			const timeoutId = setTimeout( () => {
				reject( new Error( `Request for message ${ originalMessage } timed out` ) );
				process.removeListener( 'message', handler );
			}, timeout );

			process.addListener( 'message', handler );
		} );
	}

	async #killProcess(): Promise< void > {
		const process = this.getNextProcess();
		if ( ! process || this.exitCode !== null ) {
			throw Error( 'Server process is not running. Exit code: ' + this.exitCode );
		}

		return new Promise< void >( ( resolve, reject ) => {
			process.once( 'exit', ( code ) => {
				if ( code !== 0 ) {
					reject( new Error( `Site server process exited with code ${ code } upon stopping` ) );
					return;
				}
				resolve();
			} );
			process.kill();
		} ).catch( ( error ) => {
			Sentry.captureException( error );
		} );
	}
}
