# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every week
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@automattic/*"
      - dependency-name: "@electron-forge/*"
      - dependency-name: "@wordpress/*"
      - dependency-name: "@wp-playground/*"
      - dependency-name: "@php-wasm/*"
      - dependency-name: "@types/*"
      - dependency-name: "eslint"
      - dependency-name: "eslint-*"
      - dependency-name: "@eslint/*"
      - dependency-name: "typescript-eslint"
      - dependency-name: "typescript"
      - dependency-name: "ts-*"
      - dependency-name: "jest"
      - dependency-name: "jest-*"
      - dependency-name: "patch-package"
      - dependency-name: "@playwright/*"
      - dependency-name: "electron-playwright-helpers"
      - dependency-name: "vite"
      - dependency-name: "vite-*"
      - dependency-name: "@vitejs/*"
      - dependency-name: "electron-vite"
      - dependency-name: "mdast-util-to-hast"
    groups:
      electron-forge:
        patterns:
          - "@electron-forge/*"
      wp-playground-php-wasm:
        patterns:
          - "@wp-playground/*"
          - "@php-wasm/*"
    ignore:
      - dependency-name: "eslint-plugin-studio"
      - dependency-name: "winreg" # v1.2.5 has a known issue: https://github.com/fresc81/node-winreg/issues/65

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
