# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.1.0
    - automattic/nvm#0.3.0

# All current steps use the same agent and environment; we can define them as top-level
agents:
  queue: mac
env:
  IMAGE_ID: xcode-15.2

steps:
  - label: '🔨 Create Dev Build'
    key: 'dev'
    command: |
      .buildkite/commands/prepare-environment.sh

      echo "--- :node: Building Binary"
      npm install
      node ./scripts/prepare-dev-build-version.mjs
      npm run make:macos-x64
      npm run make:macos-arm64

      .buildkite/commands/post-process-binary-for-distribution.sh

      echo "--- 🚀 Distributing Binary"
      bundle exec fastlane distribute_dev_build

    plugins: *common_plugins
    artifact_paths:
      - 'out/*.app.zip'
    if: "build.branch == 'trunk' && build.tag !~ /^v[0-9]+/"

  - label: '🔨 Create Mac Release Build'
    key: 'release-mac'
    command: |
      .buildkite/commands/prepare-environment.sh

      echo "--- :node: Building Binary"
      npm install
      node ./scripts/confirm-tag-matches-version.mjs
      npm run make:macos-x64
      npm run make:macos-arm64

      .buildkite/commands/post-process-binary-for-distribution.sh

      echo "--- 🚀 Distributing Binary"
      bundle exec fastlane distribute_release_build

    plugins: *common_plugins
    artifact_paths:
      - 'out/*.app.zip'
    if: "build.tag =~ /^v[0-9]+/"

  - label: "🔨 Create Windows Dev Build"
    key: "windows"
    command: .buildkite/commands/build-windows-dev.ps1
    artifact_paths:
      - 'C:\ProgramData\chocolatey\logs\*'
      - 'C:\build\out\Build-win32-x64\Build.exe'
    agents:
      queue: "windows"
