# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#2.17.0
    - automattic/nvm#0.3.0

  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-15.2

# This is the default pipeline – it will build the app
steps:
  #################
  # Build and Test
  #################
  - label: "🔨 Build"
    key: "build"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply

      echo "--- :testflight: Fetching Signing Certificates"
      bundle exec fastlane set_up_signing

      echo "--- :node: Building Binary"
      npm install
      npm run make:macos

      echo "--- 📃 Notarizing Binary"
      bundle exec fastlane notarize_binary

      echo "--- 🚀 Distributing Binary"
      bundle exec fastlane distribute_binary

    env: *common_env
    plugins: *common_plugins
    agents:
      queue: "mac"
    artifact_paths:
      - "out/*.app.zip"
    if: "build.branch == 'trunk'"
