# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - $CI_TOOLKIT_PLUGIN
    - $NVM_PLUGIN

# IMAGE_ID is an env var that only macOS agents need.
# Defining it at the root level propagates it too all agents, which can seem unnecessary but is a the same time convenient and DRY.
env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: "🔨 Windows Dev Build"
    key: "dev-windows"
    command: .buildkite/commands/build-for-windows-dev.ps1
    artifact_paths:
      - 'out\**\studio-setup.exe'
      - 'out\**\studio-update.nupkg'
      - 'out\**\RELEASES'
    agents:
      queue: windows
