# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - $CI_TOOLKIT_PLUGIN
    - $NVM_PLUGIN

# IMAGE_ID is an env var that only macOS agents need.
# Defining it at the root level propagates it too all agents, which can seem unnecessary but is a the same time convenient and DRY.
env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: "🔨 Windows Dev Build"
    key: "dev-windows"
    command: |
      .buildkite/commands/build-for-windows-dev.ps1
      # Download artifacts to save time when what we need to test is the appx script.
      # All the build logic has been commented out in the script above, too.
      # Not sure if these are needed, actually, but downloading them just in case...
      buildkite-agent artifact download out/make/squirrel.windows/x64/RELEASES . --build 0192dffe-8042-4bfd-a597-77fe403e4328
      buildkite-agent artifact download out/make/squirrel.windows/x64/studio-setup.exe . --build 0192dffe-8042-4bfd-a597-77fe403e4328
      buildkite-agent artifact download out/make/squirrel.windows/x64/studio-update.nupkg . --build 0192dffe-8042-4bfd-a597-77fe403e4328
      node scripts/build-appx-version.mjs
    artifact_paths:
      - 'out\**\studio-setup.exe'
      - 'out\**\studio-update.nupkg'
      - 'out\**\RELEASES'
      - 'out\**\*.appx'
      - 'out\**\*.appxbundle'
    agents:
      queue: windows
