# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.3.0
    - automattic/nvm#0.3.0

# All current steps use the same agent and environment; we can define them as top-level
agents:
  queue: mac
env:
  IMAGE_ID: xcode-15.2

steps:
  - label: Lint
    key: lint
    command: |
      .buildkite/commands/install-node-dependencies.sh
      echo '--- :eslint: Lint'
      npm run lint
    agents:
      queue: default
    plugins: *common_plugins

  - label: Unit Tests
    key: unit_tests
    command: |
      .buildkite/commands/install-node-dependencies.sh
      echo '--- :npm: Run Unit Tests'
      npm run test
    agents:
      queue: default
    plugins: *common_plugins

  # FIXME: Tests are currently failing but that's not due to CI
  # See https://github.com/Automattic/studio/issues/37
  - label: E2E Tests
    key: e2e_tests
    command: |
      .buildkite/commands/install-node-dependencies.sh
      echo '--- :package: Package app for testing'
      npm run package
      echo '--- :playwright: Run End 2 End Tests'
      npm run e2e
    plugins: *common_plugins
    agents:
      queue: "{{ matrix.queue }}"
    matrix:
      setup:
        queue:
          - mac
          - windows

  - group: "📦 Build for Mac"
    key: 'dev-mac'
    steps:
      - label: '🔨 Mac Dev Build - {{matrix}}'
        command: |
          .buildkite/commands/prepare-environment.sh

          echo "--- :node: Building Binary"
          install_npm_packages
          node ./scripts/prepare-dev-build-version.mjs
          npm run make:macos-{{matrix}}

          echo "--- 📃 Notarizing Binary"
          bundle exec fastlane notarize_binary

        plugins: *common_plugins
        artifact_paths:
          - 'out/**/*.app.zip'
        matrix:
          - "universal"
          - "x64"
          - "arm64"

  - label: "🔨 Windows Dev Build"
    key: "dev-windows"
    command: .buildkite/commands/build-windows-dev.ps1
    artifact_paths:
      - 'C:\ProgramData\chocolatey\logs\*'
      - 'out\**\studio-setup.exe'
    agents:
      queue: "windows"

  - label: ':rocket: Distribute Dev Builds'
    command: |
      echo "--- :node: Downloading Binaries"
      buildkite-agent artifact download "*.app.zip" .
      buildkite-agent artifact download "*.exe" .

      echo "--- :node: Generating Release Manifest"
      install_npm_packages
      node ./scripts/generate-releases-manifest.mjs

      echo "--- :fastlane: Distributing Dev Build"
      install_gems
      bundle exec fastlane distribute_dev_build
    agents:
      queue: "mac"
    depends_on:
      - step: "dev-mac"
      - step: "dev-windows"
    plugins: *common_plugins
    if: "build.branch == 'trunk' && build.tag !~ /^v[0-9]+/"

  - label: '🔨 Create Mac Release Build'
    key: 'release-mac'
    command: |
      .buildkite/commands/prepare-environment.sh
      .buildkite/commands/install-node-dependencies.sh

      echo "--- :node: Building Binary"
      node ./scripts/confirm-tag-matches-version.mjs
      npm run make:macos-x64
      npm run make:macos-arm64

      echo "--- 📃 Notarizing Binary"
      bundle exec fastlane notarize_binary

      .buildkite/commands/post-process-binary-for-distribution.sh

      echo "--- 🚀 Distributing Binary"
      bundle exec fastlane distribute_release_build

    plugins: *common_plugins
    artifact_paths:
      - 'out/*.app.zip'
    if: "build.tag =~ /^v[0-9]+/"
