# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# IMAGE_ID is an env var that only macOS agents need.
# Defining it at the root level propagates it too all agents, which can seem unnecessary but is a the same time convenient and DRY.
env:
  IMAGE_ID: $IMAGE_ID

steps:
  - group: 📦 Build for Windows
    key: dev-windows
    steps:
      - label: 🔨 Windows Dev Build - {{matrix}}
        agents:
          queue: windows-staging
        command: powershell -File .buildkite/commands/build-for-windows.ps1 -BuildType dev -Architecture {{matrix}}
        artifact_paths:
          - out\**\studio-setup.exe
          - out\**\studio-update.nupkg
          - out\**\RELEASES
          - out\**\*.appx
        plugins: [$CI_TOOLKIT_PLUGIN, $NVM_PLUGIN]
        matrix:
          - x64
          - arm64
