#!/bin/sh

# This file is `source`'d in CI before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# The ~> modifier is not currently used, but we check for it just in case
XCODE_VERSION=$(sed -E -n 's/^(~> )?(.*)/xcode-\2/p' .xcode-version)
CI_TOOLKIT_VERSION='6.1.0'
NVM_PLUGIN_VERSION='0.6.0'
DOCKER_PLUGIN_VERSION='v5.13.0'
NODE_VERSION=$(sed 's/^v//' .nvmrc)

export IMAGE_ID="$XCODE_VERSION"
export CI_TOOLKIT_PLUGIN="automattic/a8c-ci-toolkit#$CI_TOOLKIT_VERSION"
export NVM_PLUGIN="automattic/nvm#$NVM_PLUGIN_VERSION"
export DOCKER_PLUGIN="docker#$DOCKER_PLUGIN_VERSION"
export NODE_DOCKER_IMAGE="node:${NODE_VERSION}-bookworm"
