#!/bin/sh

# This file is `source`'d in CI before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# The ~> modifier is not currently used, but we check for it just in case
XCODE_VERSION=$(sed -E -n 's/^(~> )?(.*)/xcode-\2/p' .xcode-version)
# 🚧 [TO REVERT] Head of a8c-ci-toolkit's `ainfra-2828-expose-plugin-dir` branch (PR #224),
# so the Docker smoke-test step below can exercise `$A8C_CI_TOOLKIT_PLUGIN_DIR` before 6.3.0 ships.
CI_TOOLKIT_VERSION='e425b6287bfe8c1635a14f9ec6c276a4dfcc4c10'
NVM_PLUGIN_VERSION='0.6.0'
DOCKER_PLUGIN_VERSION='v5.13.0'
NODE_VERSION=$(sed 's/^v//' .nvmrc)
RUBY_VERSION=$(sed 's/^ruby-//' .ruby-version)

export IMAGE_ID="$XCODE_VERSION"
export CI_TOOLKIT_PLUGIN="automattic/a8c-ci-toolkit#$CI_TOOLKIT_VERSION"
export NVM_PLUGIN="automattic/nvm#$NVM_PLUGIN_VERSION"
export DOCKER_PLUGIN="docker#$DOCKER_PLUGIN_VERSION"
export NODE_DOCKER_IMAGE="node:${NODE_VERSION}-bookworm"
export RUBY_DOCKER_IMAGE="ruby:${RUBY_VERSION}-bookworm"
