name: Bug Report
description: Helps us improve our product!
labels: [ 'Needs triage', '[Type] Bug' ]
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for contributing!

        Please write a clear title, then fill in the fields below and submit.

        Please **do not** link to image hosting services such as Cloudup, Droplr, Imgur, etc…
        Instead, directly embed screenshot(s) or recording(s) in any of the text areas below: click, then drag and drop.
  - type: markdown
    attributes:
      value: |
        ---
        ## Core Information
  - type: textarea
    id: summary
    attributes:
        label: Quick summary
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Start the Studio app.
        2. Click on 'Add site'.
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected to happen
      placeholder: |
        e.g. The new site form shows up.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        e.g. Clicking the 'Add site' button does nothing.
    validations:
      required: true
  - type: dropdown
    id: users-affected
    attributes:
      label: Impact
      description: Approximately how many users are impacted?
      options:
        - One
        - Some (< 50%)
        - Most (> 50%)
        - All
    validations:
      required: true
  - type: dropdown
    id: workarounds
    attributes:
      label: Available workarounds?
      options:
        - No and the app is unusable
        - No but the app is still usable
        - Yes, difficult to implement
        - Yes, easy to implement
        - There is no user impact
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

        ## Optional Information

        The following section is optional.
  - type: dropdown
    id: site-type
    attributes:
      label: Platform
      description: (You may select more than one)
      options:
        - Mac Silicon
        - Mac Intel
        - Windows
      multiple: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or notes
      placeholder: |
        Add any information that may be relevant, such as:
          - Browser/Platform
          - Logs/Errors
