import { Type } from 'typebox';
import { runGenerator, runManifest } from 'cli/ai/tools/site-generator/generators';
import {
	contractFromManifest,
	contractVocabulary,
	reconcileMarkup,
} from 'cli/ai/tools/site-generator/identifier-contract';
import { runPooled } from 'cli/ai/tools/site-generator/llm';
import { parseManifest, type SiteManifest } from 'cli/ai/tools/site-generator/manifest';
import { themeDir, writePackageFile } from 'cli/ai/tools/site-generator/paths';
import { isSiteRunning, withDaemon, wpCli } from 'cli/ai/tools/site-generator/site-wp';
import { stripRemoteFontFaces } from 'cli/ai/tools/site-generator/theme-guards';
import { defineTool } from './define-tool';
import { resolveSite, textResult } from './utils';

// Normalize the agent-supplied spec into a JSON string. The agent should pass
// a JSON site spec; if it passes prose, wrap it so generators still get
// structured-looking input.
function normalizeSpecJson( spec: string ): string {
	const trimmed = spec.trim();
	try {
		return JSON.stringify( JSON.parse( trimmed ), null, 2 );
	} catch {
		return JSON.stringify( { description: trimmed }, null, 2 );
	}
}

export function renderFunctionsPhp( name: string, slug: string ): string {
	return `<?php
/**
 * ${ name } theme functions.
 *
 * Presentation only. All behaviour (custom post types, REST routes, blocks)
 * lives in the companion plugin, not the theme.
 *
 * @package ${ slug }
 */

add_action( 'wp_enqueue_scripts', function () {
	wp_enqueue_style(
		'${ slug }-style',
		get_parent_theme_file_uri( 'style.css' ),
		array(),
		wp_get_theme()->get( 'Version' )
	);
} );

add_action( 'after_setup_theme', function () {
	add_editor_style( 'style.css' );
} );
`;
}

function renderStyleHeader( name: string, slug: string ): string {
	return `/*
Theme Name: ${ name }
Description: A custom block theme generated by WordPress Studio.
Requires at least: 6.7
Tested up to: 6.9
Requires PHP: 7.4
Version: 0.1.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${ slug }
Tags: full-site-editing, block-patterns, block-styles, wide-blocks
*/
`;
}

// WordPress only recognises a theme when style.css carries the header block as
// its first bytes. The generator is asked to include it, but guarantee it here
// — and strip a leading BOM unconditionally, since a BOM before the header
// corrupts the parser whether or not the header is otherwise present.
export function ensureStyleHeader( css: string, name: string, slug: string ): string {
	const clean = css.charCodeAt( 0 ) === 0xfeff ? css.slice( 1 ) : css;
	if ( /Theme Name:/i.test( clean ) ) {
		return clean;
	}
	return `${ renderStyleHeader( name, slug ) }\n${ clean }`;
}

interface PlannedWrite {
	rel: string;
	run: () => Promise< string >;
}

export async function activateTheme( siteId: string, slug: string ): Promise< string > {
	return withDaemon( async () => {
		if ( ! ( await isSiteRunning( siteId ) ) ) {
			return `Site is not running — theme written but not activated. Start it (site_start), then run: wp theme activate ${ slug }`;
		}
		const result = await wpCli( siteId, [ 'theme', 'activate', slug ] );
		if ( result.exitCode !== 0 ) {
			const detail = ( result.stderr || result.stdout ).trim();
			return `Theme written but activation failed${
				detail ? `: ${ detail }` : ''
			}. Activate manually with: wp theme activate ${ slug }`;
		}
		return `Activated theme '${ slug }'.`;
	} );
}

export const generateThemeTool = defineTool(
	'generate_theme',
	'Generates a complete PURE-PRESENTATION WordPress block theme (theme.json, style.css, template parts, templates, minimal functions.php) into a site at wp-content/themes/<slug>/ and activates it. Runs the file generators in parallel from a site spec and a chosen design direction, writing the whole theme in one call. Behaviour (custom post types, REST routes, custom blocks) is NOT generated here — call generate_companion_plugin for that. Page content is NOT written as files — call seed_content to populate the live database. Returns the resolved manifest (pass it verbatim to generate_companion_plugin and seed_content). The functions.php is intentionally minimal. Best run after generate_design_previews so a design direction has been chosen.',
	{
		nameOrPath: Type.String( {
			description: 'The site name or filesystem path of the target site.',
		} ),
		spec: Type.String( {
			description:
				'The site spec as a JSON string (site type, audience, tone, layout preference, pages). Gather it with the site-spec / theme-architecture skills before calling.',
		} ),
		design: Type.Optional(
			Type.String( {
				description:
					'The chosen design direction — the first-fold HTML from generate_design_previews, or a detailed prose design brief. Strongly recommended for visual coherence.',
			} )
		),
		manifest: Type.Optional(
			Type.String( {
				description:
					'Optional file manifest as a JSON string (from a prior generate_theme call). When omitted, a manifest is generated from the spec.',
			} )
		),
	},
	async ( args ) => {
		const site = await resolveSite( args.nameOrPath );
		const specJson = normalizeSpecJson( args.spec );
		const design = args.design?.trim() || '';

		const manifest: SiteManifest = args.manifest
			? parseManifest( args.manifest )
			: await runManifest( specJson );

		const slug = manifest.themeSlug;
		const dir = themeDir( site.path, slug );
		const contract = contractFromManifest( manifest );
		const vocabulary = contractVocabulary( manifest );

		const planned: PlannedWrite[] = [
			{
				rel: 'theme.json',
				run: () =>
					runGenerator( {
						name: 'theme-json',
						specJson,
						design,
						maxTokens: 6_000,
						temperature: 0.4,
					} ),
			},
			{
				rel: 'style.css',
				run: async () =>
					ensureStyleHeader(
						await runGenerator( {
							name: 'style-css',
							specJson,
							design,
							maxTokens: 14_000,
							temperature: 0.5,
						} ),
						manifest.themeName,
						slug
					),
			},
		];

		for ( const part of manifest.parts ) {
			planned.push( {
				rel: `parts/${ part }.html`,
				run: () =>
					runGenerator( {
						name: 'template-part',
						specJson,
						design,
						task: `Part: ${ part }\nLayout mode: ${ manifest.layoutMode }\n\n${ vocabulary }`,
						maxTokens: 6_000,
						temperature: 0.5,
					} ),
			} );
		}

		for ( const template of manifest.templates ) {
			planned.push( {
				rel: `templates/${ template }.html`,
				run: () =>
					runGenerator( {
						name: 'template',
						specJson,
						design,
						task: `Template: ${ template }\nLayout mode: ${ manifest.layoutMode }\nContent mode: ${ manifest.contentMode }\n\n${ vocabulary }`,
						maxTokens: 6_000,
						temperature: 0.5,
					} ),
			} );
		}

		const generated = await runPooled(
			planned.map( ( item ) => async () => ( { rel: item.rel, content: await item.run() } ) ),
			8
		);

		const written: string[] = [];
		for ( const file of generated ) {
			// Reconcile drifted block/postType identifiers in markup files to the
			// canonical contract before writing; strip remote/file font src from
			// theme.json so fonts resolve offline (system stacks).
			let content = file.content;
			if ( file.rel.endsWith( '.html' ) ) {
				content = reconcileMarkup( file.content, contract ).html;
			} else if ( file.rel === 'theme.json' ) {
				content = stripRemoteFontFaces( file.content ).json;
			}
			await writePackageFile( dir, file.rel, content );
			written.push( file.rel );
		}
		await writePackageFile( dir, 'functions.php', renderFunctionsPhp( manifest.themeName, slug ) );
		written.push( 'functions.php' );

		const activation = await activateTheme( site.id, slug );

		const plugin = manifest.companionPlugin;
		const nextSteps: string[] = [];
		if ( plugin.needed ) {
			nextSteps.push(
				`1. generate_companion_plugin — the spec needs behaviour (${
					[
						plugin.postTypes.length ? `${ plugin.postTypes.length } post type(s)` : '',
						plugin.restRoutes.length ? `${ plugin.restRoutes.length } REST route(s)` : '',
						plugin.blocks.length ? `${ plugin.blocks.length } custom block(s)` : '',
					]
						.filter( Boolean )
						.join( ', ' ) || 'a companion plugin'
				}). Pass the manifest below.`
			);
		}
		nextSteps.push(
			`${ plugin.needed ? '2' : '1' }. seed_content — generate and publish the ${
				manifest.pages.length
			} page(s) into the database. Pass the manifest below.`
		);
		nextSteps.push(
			`${
				plugin.needed ? '3' : '2'
			}. generate_image — fill AI_IMAGE placeholders in the theme (themeSlug: ${ slug }).`
		);
		nextSteps.push(
			`${
				plugin.needed ? '4' : '3'
			}. validate_and_fix_blocks on generated content, then take_screenshot (viewport: "all") to verify and fix.`
		);

		const summary = [
			`Generated block theme '${ manifest.themeName }' at wp-content/themes/${ slug }/`,
			`Layout mode: ${ manifest.layoutMode } · Content mode: ${ manifest.contentMode }`,
			'',
			'Files written:',
			...written.map( ( f ) => `  ${ f }` ),
			'',
			activation,
			'',
			'NEXT STEPS:',
			...nextSteps.map( ( s ) => `  ${ s }` ),
			'',
			'MANIFEST (pass verbatim to the next tools):',
			JSON.stringify( manifest ),
		].join( '\n' );

		return textResult( summary );
	}
);
