// Studio's adaptor over `@mariozechner/pi-coding-agent`'s `SessionManager`.
// Owns the session-on-disk lifecycle: create new sessions inside the
// date-bucketed root, open existing files (migrating Studio-legacy JSONL on
// first read), and walk the tree for listing.
//
// Pi's own `SessionManager.create(cwd, sessionDir)` writes
// `<sessionDir>/<uuidv7>.jsonl`. We compute `<sessionDir>` per-session from
// the calendar date so files stay grouped.

import fs from 'fs/promises';
import path from 'path';
import { SessionManager } from '@mariozechner/pi-coding-agent';
import { getAiSessionsDirectoryForDate } from '@studio/common/ai/sessions/paths';
import { getAiSessionsRootDirectory } from 'cli/ai/sessions/paths';
import { STUDIO_SITES_ROOT } from 'cli/lib/site-paths';
import { migrateLegacyFileInPlace } from './legacy-migration';

export interface CreateStudioSessionOptions {
	startedAt?: Date;
}

// Create a new pi-format session JSONL under `<root>/YYYY/MM/DD/`. The
// session id is a uuidv7 generated by pi.
export async function createStudioSession(
	options: CreateStudioSessionOptions = {}
): Promise< SessionManager > {
	const startedAt = options.startedAt ?? new Date();
	const sessionDir = getAiSessionsDirectoryForDate( getAiSessionsRootDirectory(), startedAt );
	await fs.mkdir( sessionDir, { recursive: true } );
	return SessionManager.create( STUDIO_SITES_ROOT, sessionDir );
}

// Open an existing session file. Runs the Studio-legacy → pi-format
// rewrite if the file is still in the recorder's pre-pi shape.
export async function openStudioSession( filePath: string ): Promise< SessionManager > {
	await migrateLegacyFileInPlace( filePath );
	const sessionDir = path.dirname( filePath );
	return SessionManager.open( filePath, sessionDir, STUDIO_SITES_ROOT );
}

// Walk the date-bucketed root and return every JSONL file. Used by listing
// callers that want to summarize each session.
export async function listStudioSessionFiles( rootDirectory: string ): Promise< string[] > {
	async function walk( directory: string ): Promise< string[] > {
		let entries;
		try {
			entries = await fs.readdir( directory, { withFileTypes: true, encoding: 'utf8' } );
		} catch ( error ) {
			const fsError = error as NodeJS.ErrnoException;
			if ( fsError.code === 'ENOENT' ) return [];
			throw error;
		}
		const nested = await Promise.all(
			entries.map( async ( entry ) => {
				const fullPath = path.join( directory, entry.name );
				if ( entry.isDirectory() ) return walk( fullPath );
				if ( entry.isFile() && entry.name.endsWith( '.jsonl' ) ) return [ fullPath ];
				return [];
			} )
		);
		return nested.flat();
	}
	return walk( rootDirectory );
}
