// src/lib/replicate/local-data/card-render-php.ts
//
// Generate the mu-plugin that registers the `dla/data-card` dynamic block. The
// block renders ONE CPT post into the source-faithful card markup at request
// time (frontend + editor via ServerSideRender) by applying the DataCard
// template's data-dla-* bindings — the PHP mirror of card-render.ts. The
// template, lookup maps, term labels and field list are baked in so the plugin
// is self-contained on the WP install (data-model.json lives only in the build).
//
// A php-execution parity test (card-render-php.test.ts) renders the same item
// through this PHP and through the TS mirror and asserts the DOMs match, so the
// two implementations cannot silently drift.
import type { DataModel } from './types.js';

import { phpLiteral as php } from './string-utils.js';

/** Render a JS map as a PHP associative-array body (key => value pairs). */
function phpAssoc(obj: Record<string, string>, indent: string): string {
  const rows = Object.entries(obj).map(
    ([k, v]) => `${indent}${php(k)} => ${php(v)},`,
  );
  return rows.join('\n');
}

/** Render variant template map entries as nowdocs, with stable key ordering. */
function phpTemplateAssoc(obj: Record<string, string>, indent: string): string {
  return Object.entries(obj)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v], i) => `${indent}${php(k)} => <<<'DLAVAR${i}'\n${v.trim()}\nDLAVAR${i}\n${indent},`)
    .join('\n');
}

/** Conventional mu-plugin filename for the card block. */
export function dataCardPluginFilename(model: DataModel): string {
  return `dla-data-${model.cpt.slug}-card.php`;
}

/**
 * Build the mu-plugin PHP that registers dla/data-card. Requires model.card;
 * throws if absent (the caller gates on a card spec being present).
 */
export function buildDataCardPlugin(model: DataModel): string {
  const card = model.card;
  if (!card) throw new Error('buildDataCardPlugin: model.card is required');

  const taxSlug = model.taxonomy.slug;
  const fieldKeys = model.fields.map((f) => f.key);
  const termLabels: Record<string, string> = {};
  for (const t of model.taxonomy.terms) termLabels[t.slug] = t.label;

  const mapsBody = Object.entries(card.maps)
    .map(
      ([name, table]) =>
        `        ${php(name)} => array(\n${phpAssoc(table, '            ')}\n        ),`,
    )
    .join('\n');
  const variantsBody = phpTemplateAssoc(card.variants ?? {}, '        ');

  const labelsBody = phpAssoc(termLabels, '        ');
  const fieldsBody = fieldKeys.map((k) => `        ${php(k)},`).join('\n');

  // Editor registration JS (inline, no build step): ServerSideRender preview so
  // the card shows inside the query loop in the block editor.
  const editorJs = `( function( blocks, element, srModule ) {
  var ServerSideRender = srModule && ( srModule.default || srModule );
  blocks.registerBlockType( 'dla/data-card', {
    apiVersion: 3,
    title: 'Data Card',
    category: 'theme',
    icon: 'id-alt',
    usesContext: [ 'postId' ],
    attributes: { variant: { type: 'string', default: '' } },
    edit: function( props ) {
      return element.createElement( ServerSideRender, {
        block: 'dla/data-card',
        attributes: props.attributes,
        urlQueryArgs: { post_id: props.context.postId }
      } );
    },
    save: function() { return null; }
  } );
} )( window.wp.blocks, window.wp.element, window.wp.serverSideRender );`;

  return `<?php
/**
 * Plugin Name: DLA Data Card — ${model.cpt.plural}
 * Description: Registers the dla/data-card dynamic block rendering one ${model.cpt.slug} post into source-faithful card markup (generated by liberate-local).
 *
 * GENERATED FILE — do not edit by hand; re-run the conversion to regenerate.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'DLA_CARD_TEMPLATE_${model.cpt.slug}', <<<'DLATPL'
${card.template.trim()}
DLATPL
);

/** Named alternate card templates keyed by dla/data-card variant. */
function dla_card_variants_${model.cpt.slug}() {
    return array(
${variantsBody}
    );
}

/** Named lookup tables referenced by the card template's map.<name>.<expr>. */
function dla_card_maps_${model.cpt.slug}() {
    return array(
${mapsBody}
    );
}

/** Taxonomy term slug -> human label (baked from the data model). */
function dla_card_term_label_${model.cpt.slug}( $slug ) {
    $labels = array(
${labelsBody}
    );
    return isset( $labels[ $slug ] ) ? $labels[ $slug ] : $slug;
}

/** Build the render item (id, title, content, terms, meta, gallery) from a post. */
function dla_card_build_item_${model.cpt.slug}( $post_id ) {
    $meta = array();
    foreach ( array(
${fieldsBody}
    ) as $key ) {
        $meta[ $key ] = get_post_meta( $post_id, $key, true );
    }
    $terms = wp_get_post_terms( $post_id, ${php(taxSlug)}, array( 'fields' => 'slugs' ) );
    if ( is_wp_error( $terms ) ) { $terms = array(); }
    $gallery = get_post_meta( $post_id, '_dla_gallery', true );
    // The source mockup points every card at one static detail page; the live
    // card must link to THIS post's permalink (and its term archive) instead.
    $cat_url = '';
    if ( isset( $terms[0] ) ) {
        $link = get_term_link( $terms[0], ${php(taxSlug)} );
        if ( ! is_wp_error( $link ) ) { $cat_url = $link; }
    }
    return array(
        'id'        => (string) get_post_meta( $post_id, '_dla_item_id', true ),
        'title'     => get_the_title( $post_id ),
        'content'   => get_post_field( 'post_content', $post_id ),
        'terms'     => array_values( $terms ),
        'meta'      => $meta,
        'gallery'   => is_array( $gallery ) ? $gallery : array(),
        'permalink' => (string) get_permalink( $post_id ),
        'cat_url'   => (string) $cat_url,
    );
}

/** Resolve a binding expression against a render item. Mirrors card-render.ts. */
function dla_card_resolve_${model.cpt.slug}( $expr, $item, $maps ) {
    $e = trim( $expr );
    if ( preg_match( "/^'(.*)'$/", $e, $m ) ) { return $m[1]; }
    if ( 'id' === $e ) { return (string) $item['id']; }
    if ( 'title' === $e ) { return (string) $item['title']; }
    if ( 'content' === $e ) { return (string) ( isset( $item['content'] ) ? $item['content'] : '' ); }
    if ( 'cat.slug' === $e ) { return (string) ( isset( $item['terms'][0] ) ? $item['terms'][0] : '' ); }
    if ( 'cat.label' === $e ) { return isset( $item['terms'][0] ) ? dla_card_term_label_${model.cpt.slug}( $item['terms'][0] ) : ''; }
    if ( 'permalink' === $e ) { return (string) ( isset( $item['permalink'] ) ? $item['permalink'] : '' ); }
    if ( 'cat.url' === $e ) { return (string) ( isset( $item['cat_url'] ) ? $item['cat_url'] : '' ); }
    if ( preg_match( '/^meta\\.(.+)$/', $e, $m ) ) {
        $v = isset( $item['meta'][ $m[1] ] ) ? $item['meta'][ $m[1] ] : '';
        if ( is_bool( $v ) ) { return $v ? '1' : ''; }
        return (string) $v;
    }
    if ( preg_match( '/^gallery\\.(\\d+)\\.caption$/', $e, $m ) ) {
        $i = (int) $m[1];
        return (string) ( isset( $item['gallery'][ $i ]['caption'] ) ? $item['gallery'][ $i ]['caption'] : '' );
    }
    if ( preg_match( '/^map\\.([^.]+)\\.(.+)$/', $e, $m ) ) {
        $table = isset( $maps[ $m[1] ] ) ? $maps[ $m[1] ] : array();
        $key   = dla_card_resolve_${model.cpt.slug}( $m[2], $item, $maps );
        return isset( $table[ $key ] ) ? $table[ $key ] : '';
    }
    return '';
}

/** Evaluate a data-dla-if condition. Mirrors card-render.ts evalCond. */
function dla_card_cond_${model.cpt.slug}( $cond, $item, $maps ) {
    if ( preg_match( "/^(.+?)!=('[^']*')$/", $cond, $m ) ) {
        return dla_card_resolve_${model.cpt.slug}( $m[1], $item, $maps ) !== dla_card_resolve_${model.cpt.slug}( $m[2], $item, $maps );
    }
    if ( preg_match( "/^(.+?)==('[^']*')$/", $cond, $m ) ) {
        return dla_card_resolve_${model.cpt.slug}( $m[1], $item, $maps ) === dla_card_resolve_${model.cpt.slug}( $m[2], $item, $maps );
    }
    return '' !== dla_card_resolve_${model.cpt.slug}( $cond, $item, $maps );
}

/** Apply the template's data-dla-* bindings to one item -> card HTML. */
function dla_card_render_${model.cpt.slug}( $template, $maps, $item ) {
    $doc = new DOMDocument( '1.0', 'UTF-8' );
    libxml_use_internal_errors( true );
    $doc->loadHTML(
        '<?xml encoding="utf-8" ?><div id="dla-root">' . $template . '</div>',
        LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
    );
    libxml_clear_errors();
    $xp = new DOMXPath( $doc );

    // Conditionals first; resolve one at a time so removing a parent drops its
    // (now-detached) descendants instead of binding into dead nodes.
    while ( ( $node = $xp->query( '//*[@data-dla-if]' )->item( 0 ) ) !== null ) {
        if ( dla_card_cond_${model.cpt.slug}( $node->getAttribute( 'data-dla-if' ), $item, $maps ) ) {
            $node->removeAttribute( 'data-dla-if' );
        } else {
            $node->parentNode->removeChild( $node );
        }
    }
    foreach ( iterator_to_array( $xp->query( '//*[@data-dla-attr]' ) ) as $node ) {
        $spec = $node->getAttribute( 'data-dla-attr' );
        $node->removeAttribute( 'data-dla-attr' );
        foreach ( explode( ',', $spec ) as $pair ) {
            $i = strpos( $pair, ':' );
            if ( false === $i ) { continue; }
            $name = trim( substr( $pair, 0, $i ) );
            $val  = dla_card_resolve_${model.cpt.slug}( substr( $pair, $i + 1 ), $item, $maps );
            if ( '' !== $name ) { $node->setAttribute( $name, $val ); }
        }
    }
    foreach ( iterator_to_array( $xp->query( '//*[@data-dla-class]' ) ) as $node ) {
        $cls = dla_card_resolve_${model.cpt.slug}( $node->getAttribute( 'data-dla-class' ), $item, $maps );
        $node->removeAttribute( 'data-dla-class' );
        if ( '' !== $cls ) {
            $existing = $node->getAttribute( 'class' );
            $node->setAttribute( 'class', trim( $existing . ' ' . $cls ) );
        }
    }
    foreach ( iterator_to_array( $xp->query( '//*[@data-dla-text]' ) ) as $node ) {
        $txt = dla_card_resolve_${model.cpt.slug}( $node->getAttribute( 'data-dla-text' ), $item, $maps );
        $node->removeAttribute( 'data-dla-text' );
        while ( $node->firstChild ) { $node->removeChild( $node->firstChild ); }
        $node->appendChild( $doc->createTextNode( $txt ) );
    }

    $roots = $xp->query( '//*[@id="dla-root"]' );
    $root  = $roots->item( 0 );
    if ( ! $root ) { return ''; }
    $html = '';
    foreach ( $root->childNodes as $child ) { $html .= $doc->saveHTML( $child ); }
    return trim( $html );
}

/** render_callback for dla/data-card. */
function dla_card_block_render_${model.cpt.slug}( $attributes, $content, $block ) {
    $post_id = 0;
    if ( $block && isset( $block->context['postId'] ) ) {
        $post_id = (int) $block->context['postId'];
    } elseif ( isset( $_GET['post_id'] ) ) {
        $post_id = (int) $_GET['post_id'];
    } else {
        $post_id = (int) get_the_ID();
    }
    if ( ! $post_id ) { return ''; }
    $item = dla_card_build_item_${model.cpt.slug}( $post_id );
    $variant = isset( $attributes['variant'] ) ? (string) $attributes['variant'] : '';
    $variants = dla_card_variants_${model.cpt.slug}();
    $template = ( '' !== $variant && isset( $variants[ $variant ] ) )
        ? $variants[ $variant ]
        : constant( 'DLA_CARD_TEMPLATE_${model.cpt.slug}' );
    $html = dla_card_render_${model.cpt.slug}(
        $template,
        dla_card_maps_${model.cpt.slug}(),
        $item
    );

    // Per-card JSON data island so client JS (e.g. the detail modal) can read
    // the WordPress-driven record from the DOM instead of a stale source array.
    $island = $item;
    $island['termLabels'] = array();
    foreach ( $item['terms'] as $slug ) {
        $island['termLabels'][ $slug ] = dla_card_term_label_${model.cpt.slug}( $slug );
    }
    $script = '<script type="application/json" class="dla-item" data-id="'
        . esc_attr( $item['id'] ) . '">' . wp_json_encode( $island ) . '</script>';

    return $html . $script;
}

add_action( 'init', function () {
    register_block_type( 'dla/data-card', array(
        'api_version'     => 3,
        'uses_context'    => array( 'postId' ),
        'attributes'      => array(
            'variant' => array( 'type' => 'string', 'default' => '' ),
        ),
        'render_callback' => 'dla_card_block_render_${model.cpt.slug}',
    ) );
} );

add_action( 'enqueue_block_editor_assets', function () {
    $handle = 'dla-data-card-${model.cpt.slug}-editor';
    wp_register_script( $handle, '', array( 'wp-blocks', 'wp-element', 'wp-server-side-render' ), null, true );
    wp_enqueue_script( $handle );
    wp_add_inline_script( $handle, ${php(editorJs)} );
} );
`;
}
