// src/lib/replicate/local-data/cpt-plugin.ts
//
// Generate a self-contained mu-plugin that registers the CPT + taxonomy + meta
// for the WordPress-driven data path. A mu-plugin (not a one-shot wp-cli call)
// because registration must run on EVERY request — the query loops, REST, and
// block bindings all need the type/taxonomy/meta registered at init, not just
// when posts were inserted. show_in_rest is on everywhere so the block editor's
// query loop + bindings can see the data.
import type { DataModel } from './types.js';

import { phpLiteral as php } from './string-utils.js';

/** A PHP-safe identifier fragment from a slug (for the sanitize fn name). */
function phpId(slug: string): string {
  const id = slug.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(id) ? id : `dla_${id}`;
}

/** REST `show_in_rest` value for a field: a typed schema when a string format
 * maps to a standard REST format, else bare true. */
function restSchema(f: DataModel['fields'][number]): string {
  const restFormat = f.format === 'email' ? 'email' : f.format === 'url' ? 'uri' : '';
  if (f.type === 'string' && restFormat) {
    return `array( 'schema' => array( 'type' => 'string', 'format' => ${php(restFormat)} ) )`;
  }
  return 'true';
}

/**
 * Build the mu-plugin PHP source registering the model's CPT, taxonomy, and
 * per-field post meta. Deterministic + idempotent (WP register_* are safe to
 * call every init). The plugin slug/text is derived from the CPT slug.
 *
 * Each meta field gets a per-type/format sanitize_callback and (for email/url
 * string fields) a typed REST schema, so values are coerced/cleaned on write
 * and self-describe over REST — adopted from wordpress-block-design-compiler's
 * content-model sanitization.
 */
export function buildCptMuPlugin(model: DataModel): string {
  const { cpt, taxonomy, fields } = model;
  const BUILTIN_TYPES = new Set(['post', 'page', 'attachment']);
  const BUILTIN_TAX = new Set(['category', 'post_tag']);
  const registerType = !BUILTIN_TYPES.has(cpt.slug);
  const registerTax = !BUILTIN_TAX.has(taxonomy.slug);
  const supports = `array( ${cpt.supports.map((s) => php(s)).join(', ')} )`;
  const fn = `dla_cpt_sanitize_${phpId(cpt.slug)}`;

  const metaRegistrations = fields
    .map((f) => {
      const desc = f.label ? `\n        'description'       => ${php(f.label)},` : '';
      return (
        `    register_post_meta( ${php(cpt.slug)}, ${php(f.key)}, array(\n` +
        `        'type'              => ${php(f.type)},\n` +
        `        'single'           => true,\n` +
        `        'show_in_rest'     => ${restSchema(f)},` +
        desc +
        `\n        'sanitize_callback' => function ( $value ) { return ${fn}( $value, ${php(f.type)}, ${php(f.format ?? '')} ); },\n` +
        `    ) );`
      );
    })
    .join('\n');

  // Shared sanitize helper (mirrors the DataField type/format contract).
  const sanitizeFn = `function ${fn}( $value, $type, $format ) {
    switch ( $type ) {
        case 'boolean': return rest_sanitize_boolean( $value );
        case 'integer': return intval( $value );
        case 'number':  return is_numeric( $value ) ? (float) $value : 0;
        case 'string':
        default:
            if ( 'email' === $format )    return sanitize_email( $value );
            if ( 'url' === $format )      return esc_url_raw( $value );
            if ( 'textarea' === $format ) return sanitize_textarea_field( $value );
            return sanitize_text_field( $value );
    }
}`;

  const typeRegistration = `    register_post_type( ${php(cpt.slug)}, array(
        'labels'       => array(
            'name'          => ${php(cpt.plural)},
            'singular_name' => ${php(cpt.singular)},
        ),
        'public'       => ${cpt.public ? 'true' : 'false'},
        'has_archive'  => ${cpt.public ? 'true' : 'false'},
        'show_in_rest' => true,
        'supports'     => ${supports},
        'menu_icon'    => 'dashicons-archive',
    ) );`;

  const taxRegistration = `    register_taxonomy( ${php(taxonomy.slug)}, ${php(cpt.slug)}, array(
        'labels'            => array(
            'name'          => ${php(taxonomy.label)},
            'singular_name' => ${php(taxonomy.label)},
        ),
        'public'            => true,
        'hierarchical'      => ${taxonomy.hierarchical ? 'true' : 'false'},
        'show_in_rest'      => true,
        'show_admin_column' => true,
    ) );`;

  const initBody = [registerType ? typeRegistration : '', registerTax ? taxRegistration : '', metaRegistrations]
    .filter(Boolean)
    .join('\n\n');

  return `<?php
/**
 * Plugin Name: DLA Data — ${cpt.plural}
 * Description: Registers the ${cpt.slug} post type, ${taxonomy.slug} taxonomy, and meta for the WordPress-driven data path (generated by liberate-local).
 *
 * GENERATED FILE — do not edit by hand; re-run the conversion to regenerate.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

${sanitizeFn}

add_action( 'init', function () {
${initBody}
} );

add_filter( 'query_loop_block_query_vars', function ( $query, $block ) {
    $attrs = isset( $block->parsed_block['attrs'] ) ? $block->parsed_block['attrs'] : array();
    if ( empty( $attrs['dlaTermSlug'] ) || empty( $attrs['dlaTaxonomy'] ) ) { return $query; }
    $tax = (array) ( isset( $query['tax_query'] ) ? $query['tax_query'] : array() );
    $tax[] = array(
        'taxonomy' => sanitize_key( $attrs['dlaTaxonomy'] ),
        'field'    => 'slug',
        'terms'    => array( sanitize_title( $attrs['dlaTermSlug'] ) ),
    );
    $query['tax_query'] = $tax;
    return $query;
}, 10, 2 );
`;
}

/** Conventional mu-plugin filename for a model (under wp-content/mu-plugins/). */
export function cptMuPluginFilename(model: DataModel): string {
  return `dla-data-${model.cpt.slug}.php`;
}
