import fs from 'fs';
import path from 'path';

// Abstract base class for SQLite integration across different contexts
export abstract class SqliteIntegrationProvider {
	abstract getSqliteDirname(): string;
	protected abstract getSqlitePluginSourcePath(): string;

	async isSqliteIntegrationAvailable(): Promise< boolean > {
		const sqliteSourcePath = this.getSqlitePluginSourcePath();
		const dbCopyPath = path.join( sqliteSourcePath, 'db.copy' );
		return fs.existsSync( sqliteSourcePath ) && fs.existsSync( dbCopyPath );
	}

	// Returns true if site has db.php or no wp-config.php
	async needsSqliteSetup( sitePath: string ): Promise< boolean > {
		const hasDbPhp = fs.existsSync( path.join( sitePath, 'wp-content', 'db.php' ) );
		const hasWpConfig = fs.existsSync( path.join( sitePath, 'wp-config.php' ) );
		return hasDbPhp || ! hasWpConfig;
	}

	/**
	 * Check if the existing db.php is a custom drop-in that should not be overwritten.
	 *
	 * A custom drop-in is one that defines SQLITE_DB_DROPIN_VERSION but was not
	 * generated by Studio. This allows plugins like markdown-database-integration
	 * to extend the SQLite integration with a custom db.php while still using the
	 * same SQLite mu-plugin machinery.
	 *
	 * We detect this by checking whether the db.php file was auto-generated from
	 * db.copy (contains the SQLITE_IMPLEMENTATION_FOLDER_PATH placeholder pattern)
	 * or is a custom file that defines the version constant on its own.
	 */
	async hasCustomDbDropin( sitePath: string ): Promise< boolean > {
		const dbPhpPath = path.join( sitePath, 'wp-content', 'db.php' );
		if ( ! fs.existsSync( dbPhpPath ) ) {
			return false;
		}

		try {
			const content = await fs.promises.readFile( dbPhpPath, 'utf8' );

			// The stock db.php (generated from db.copy) contains this comment
			// identifying it as auto-generated by the SQLite integration plugin.
			const isStockDropin = content.includes(
				'This file is auto-generated and copied from the sqlite plugin'
			);

			// A custom drop-in defines SQLITE_DB_DROPIN_VERSION but is not the
			// stock file. It extends or replaces the SQLite integration layer.
			const definesVersion = content.includes( 'SQLITE_DB_DROPIN_VERSION' );

			return definesVersion && ! isStockDropin;
		} catch {
			return false;
		}
	}

	async getSqliteVersionFromInstallation( sqliteMuPluginPath: string ): Promise< string > {
		try {
			const versionFileContent = await fs.promises.readFile(
				path.join( sqliteMuPluginPath, 'load.php' ),
				'utf8'
			);
			const matches = versionFileContent.match( /\s\*\sVersion:\s*([0-9a-zA-Z.-]+)/ );
			return matches?.[ 1 ] || '';
		} catch ( err ) {
			return '';
		}
	}

	async installSqliteIntegration( sitePath: string ): Promise< void > {
		if ( ! ( await this.isSqliteIntegrationAvailable() ) ) {
			throw new Error( 'SQLite integration files not found.' );
		}

		const wpContentPath = path.join( sitePath, 'wp-content' );
		const databasePath = path.join( wpContentPath, 'database' );

		await fs.promises.mkdir( databasePath, { recursive: true } );

		// Only write db.php if there is no custom drop-in. Custom drop-ins
		// extend the SQLite integration (e.g. markdown-database-integration)
		// and should not be overwritten.
		const hasCustom = await this.hasCustomDbDropin( sitePath );
		if ( ! hasCustom ) {
			const sqliteSourcePath = this.getSqlitePluginSourcePath();
			const dbCopyContent = await fs.promises.readFile(
				path.join( sqliteSourcePath, 'db.copy' ),
				'utf8'
			);
			const sqliteDirname = this.getSqliteDirname();
			const updatedContent = dbCopyContent.replace(
				"'{SQLITE_IMPLEMENTATION_FOLDER_PATH}'",
				`realpath( __DIR__ . '/mu-plugins/${ sqliteDirname }' )`
			);
			await fs.promises.writeFile( path.join( wpContentPath, 'db.php' ), updatedContent );
		}

		// Always keep the SQLite mu-plugin updated — custom drop-ins depend on
		// the mu-plugin's driver classes even when they replace db.php.
		const sqliteSourcePath = this.getSqlitePluginSourcePath();
		const sqliteDirname = this.getSqliteDirname();
		const sqliteDestPath = path.join( wpContentPath, 'mu-plugins', sqliteDirname );
		await fs.promises.rm( sqliteDestPath, { recursive: true, force: true } );
		await fs.promises.cp( sqliteSourcePath, sqliteDestPath, {
			recursive: true,
			verbatimSymlinks: true,
		} );
	}

	async keepSqliteIntegrationUpdated( sitePath: string ): Promise< boolean > {
		if ( await this.needsSqliteSetup( sitePath ) ) {
			await this.installSqliteIntegration( sitePath );
			return true;
		}
		return false;
	}

	async isSqliteInstalled( sitePath: string ): Promise< boolean > {
		return (
			fs.existsSync( path.join( sitePath, 'wp-content', 'mu-plugins', this.getSqliteDirname() ) ) &&
			fs.existsSync( path.join( sitePath, 'wp-content', 'db.php' ) )
		);
	}
}
