// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Defined in webpack.main.config.ts
declare const COMMIT_HASH: string | undefined;

interface ShowNotificationOptions extends Electron.NotificationConstructorOptions {
	showIcon: boolean;
}

interface StoppedSiteDetails {
	running: false;

	id: string;
	name: string;
	path: string;
	port: number;
	phpVersion: string;
	wpVersion?: string;
	customDomain?: string;
	enableHttps?: boolean;
	adminPassword?: string;
	tlsKey?: string;
	tlsCert?: string;
	themeDetails?: {
		name: string;
		path: string;
		slug: string;
		isBlockTheme: boolean;
		supportsWidgets: boolean;
		supportsMenus: boolean;
	};
	isAddingSite?: boolean;
	autoStart?: boolean;
}

interface StartedSiteDetails extends StoppedSiteDetails {
	running: true;

	url: string;
}

type SiteDetails = StartedSiteDetails | StoppedSiteDetails;

interface Snapshot {
	url: string;
	atomicSiteId: number;
	localSiteId: string;
	date: number;
	isLoading?: boolean;
	isDeleting?: boolean;
	name?: string;
	sequence?: number;
	userId?: number;
}

type InstalledApps = {
	vscode: boolean | null;
	phpstorm: boolean | null;
};

type WithoutIpcEvent< T extends unknown[] > = T extends [ unknown, ...infer Rest ] ? Rest : [];
type ToPromise< T > = T extends Promise< unknown > ? T : Promise< T >;
type IpcHandlers = typeof import('./ipc-handlers');

// IpcApi functions have the same signatures as the functions in ipc-handlers.ts, except
// with the first parameter removed.
type IpcApi = Omit<
	{
		[ K in keyof IpcHandlers ]: (
			...args: WithoutIpcEvent< Parameters< IpcHandlers[ K ] > >
		) => ToPromise< ReturnType< IpcHandlers[ K ] > >;
	},
	'logRendererMessage'
> & {
	// `webUtils.getPathForFile` is available only inside preload script, that's why this one
	// function is exception and need to be defined here manually. See
	// https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-320
	getPathForFile: ( file: File ) => string;
	logRendererMessage: (
		...args: WithoutIpcEvent< Parameters< IpcHandlers[ 'logRendererMessage' ] > >
	) => void;
};

interface AppGlobals {
	platform: NodeJS.Platform;
	appName: string;
	appVersion: string;
	arm64Translation: boolean;
	terminalWpCliEnabled: boolean;
}

// Our IPC objects will be attached to the `window` global
interface Window {
	ipcApi: IpcApi;
	appGlobals: AppGlobals;
}

// Network
interface WpcomNetworkError extends Error {
	code: string;
	status: number;
}
