// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Defined in webpack.main.config.ts
declare const COMMIT_HASH: string | undefined;

interface ShowNotificationOptions extends Electron.NotificationConstructorOptions {
	showIcon: boolean;
}

interface StoppedSiteDetails {
	running: false;

	id: string;
	name: string;
	path: string;
	port: number;
	phpVersion: string;
	isWpAutoUpdating?: boolean;
	customDomain?: string;
	enableHttps?: boolean;
	adminPassword?: string;
	tlsKey?: string;
	tlsCert?: string;
	themeDetails?: {
		name: string;
		path: string;
		slug: string;
		isBlockTheme: boolean;
		supportsWidgets: boolean;
		supportsMenus: boolean;
	};
	isAddingSite?: boolean;
	autoStart?: boolean;
}

interface StartedSiteDetails extends StoppedSiteDetails {
	running: true;

	url: string;
}

type SiteDetails = StartedSiteDetails | StoppedSiteDetails;

type InstalledApps = {
	vscode: boolean;
	phpstorm: boolean;
	webstorm: boolean;
	windsurf: boolean;
	cursor: boolean;
};

type InstalledTerminals = {
	terminal: boolean;
	iterm: boolean;
};

type WithoutIpcEvent< T extends unknown[] > = T extends [ unknown, ...infer Rest ] ? Rest : [];
type ToPromise< T > = T extends Promise< unknown > ? T : Promise< T >;
type IpcHandlers = typeof import('./ipc-handlers');

// Define which handlers use `ipcRenderer.send` in `src/preload.ts`
type NonPromiseHandlers =
	| 'logRendererMessage'
	| 'showNotification'
	| 'openSiteURL'
	| 'openURL'
	| 'showErrorMessageBox'
	| 'addSyncOperation'
	| 'clearSyncOperation'
	| 'openLocalPath'
	| 'showItemInFolder';

// IpcApi functions have the same signatures as the functions in ipc-handlers.ts, except
// with the first parameter removed.
type IpcApi = {
	[ K in keyof IpcHandlers ]: (
		...args: WithoutIpcEvent< Parameters< IpcHandlers[ K ] > >
	) => K extends NonPromiseHandlers ? void : ToPromise< ReturnType< IpcHandlers[ K ] > >;
} & {
	// `webUtils.getPathForFile` is available only inside preload script, that's why this one
	// function is exception and need to be defined here manually. See
	// https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-320
	getPathForFile: ( file: File ) => string;
};

interface AppGlobals {
	platform: NodeJS.Platform;
	appName: string;
	appVersion: string;
	arm64Translation: boolean;
	pressableSyncEnabled: boolean;
	terminalWpCliEnabled: boolean;
	preferredEditor: boolean;
}

// Our IPC objects will be attached to the `window` global
interface Window {
	ipcApi: IpcApi;
	appGlobals: AppGlobals;
}

// Network
interface WpcomNetworkError extends Error {
	code: string;
	status: number;
}
