# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

env:
  IMAGE_ID: $IMAGE_ID

priority: 1

steps:
  - label: ":checkered_flag: Finalize Release"
    plugins: [$CI_TOOLKIT_PLUGIN, $NVM_PLUGIN]
    command: |
      echo "--- :robot_face: Use bot for Git operations"
      source use-bot-for-git

      checkout_release_branch "${RELEASE_VERSION}"

      echo "--- :ruby: Setup Ruby Tools"
      install_gems

      echo "--- :checkered_flag: Finalize Release"
      bundle exec fastlane finalize_release version:"${RELEASE_VERSION}" skip_confirm:true
    agents:
      queue: mac
    retry:
      manual:
        reason: If release jobs fail, you should always re-trigger the task from Releases V2 rather than retrying the individual job from Buildkite
        allowed: false
