name: Auto Author Assign

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    if: ${{ github.actor != 'wpmobilebot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@bdd7688cbf9e6d5683f02f8c7d8ae4062a254b6d # v3.0.2
