name: Performance Metrics Comparison

on:
  pull_request:
  push:
    branches: [trunk]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  metrics:
    name: Run metrics tests
    runs-on: macos-13
    permissions:
      contents: read
    env:
      ARTIFACTS_PATH: ${{ github.workspace }}/artifacts
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Compare performance with trunk
        if: github.event_name == 'pull_request'
        run: cd scripts/compare-perf && npm ci && npm run compare -- perf $GITHUB_SHA b966f334fc38f0f8d57cecea3ef190b2721dc2db --tests-branch $GITHUB_SHA

      - name: Compare performance with base branch
        if: github.event_name == 'push'
        # The base hash used here need to be a commit that is compatible with the current performance tests.
        # The current one is c954cc2228eab819118ab6e84e22dd0223faacfe
        # it needs to be updated every time it becomes unsupported by the current performance tests.
        # It is used as a base comparison point to avoid fluctuation in the performance metrics.
        run: |
          cd scripts/compare-perf && npm ci && npm run compare -- perf $GITHUB_SHA b966f334fc38f0f8d57cecea3ef190b2721dc2db --tests-branch $GITHUB_SHA
      - name: Archive performance results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: ${{ env.WP_ARTIFACTS_PATH }}/*.performance-results*.json
